% U.S. Geological Survey Report LaTeX class file
%------------------------ identification ------------------
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{usgsreport}[2006/12/03 (W. Asquith)]
%------------------------ initial code --------------------
%------------------------ declaration of options ----------
%------------------------ execution of options
\ProcessOptions \relax
%------------------------ package loading -----------------
\LoadClassWithOptions{article}
%------------------------ main code -----------------------

\endinput
